const loginView=document.getElementById('loginView');
const dashboardView=document.getElementById('dashboardView');
const form=document.getElementById('loginForm');
const message=document.getElementById('loginMessage');
const demoButton=document.getElementById('demoLoginButton');
const STORAGE_KEY='ftnVendorOrdersV0231';
const SOUND_KEY='ftnVendorSound';
let soundOn=localStorage.getItem(SOUND_KEY)!=='off';

function showDashboard(){loginView.classList.add('hidden-view');dashboardView.classList.remove('hidden-view');document.body.classList.remove('login-page');localStorage.setItem('ftnVendorLoggedIn','true');orders=loadOrders();render();}
function showLogin(){dashboardView.classList.add('hidden-view');loginView.classList.remove('hidden-view');document.body.classList.add('login-page');localStorage.removeItem('ftnVendorLoggedIn');}
form.addEventListener('submit',e=>{e.preventDefault();const email=document.getElementById('email').value.trim().toLowerCase();const password=document.getElementById('password').value.trim();if(email==='vendor@foodtreknow.com'&&password==='demo123'){message.textContent='';showDashboard();}else message.textContent='Login not recognized. Use vendor@foodtreknow.com and demo123.';});
if(demoButton)demoButton.addEventListener('click',()=>{document.getElementById('email').value='vendor@foodtreknow.com';document.getElementById('password').value='demo123';message.textContent='';});

const now=Date.now();
const seedOrders=[
{id:1025,customer:'Kevin',items:[{name:'Cheeseburger',qty:2,price:9.50},{name:'Fries',qty:1,price:4.00},{name:'Lemonade',qty:1,price:4.50}],subtotal:27.50,tax:1.65,total:29.15,status:'new',time:'6:12 PM',payment:'Credit Card',paid:true,createdAt:now-90000},
{id:1026,customer:'Ashley',items:[{name:'Chicken Tacos',qty:3,price:5.25},{name:'Bottled Water',qty:1,price:3.00}],subtotal:18.75,tax:1.13,total:19.88,status:'new',time:'6:15 PM',payment:'Apple Pay',paid:true,createdAt:now-45000},
{id:1023,customer:'Marcus',items:[{name:'Turkey Burger',qty:1,price:13.00},{name:'Sweet Potato Fries',qty:1,price:9.00}],subtotal:22.00,tax:1.32,total:23.32,status:'preparing',time:'6:02 PM',payment:'Google Pay',paid:true,createdAt:now-720000,acceptedAt:now-420000},
{id:1022,customer:'Danielle',items:[{name:'Fish Tacos',qty:2,price:9.00},{name:'Soda',qty:1,price:6.00}],subtotal:24.00,tax:1.44,total:25.44,status:'ready',time:'5:54 PM',payment:'Credit Card',paid:true,createdAt:now-960000,acceptedAt:now-720000,readyAt:now-150000},
{id:1021,customer:'James',items:[{name:'BBQ Platter',qty:1,price:34.00}],subtotal:34.00,tax:2.04,total:36.04,status:'pickedup',time:'5:41 PM',payment:'Credit Card',paid:true,createdAt:now-1800000,acceptedAt:now-1500000,readyAt:now-1100000,pickedUpAt:now-15000},
{id:1020,customer:'Maya',items:[{name:'Loaded Nachos',qty:2,price:12.00}],subtotal:24.00,tax:1.44,total:25.44,status:'completed',time:'5:30 PM',payment:'Cash App',paid:true,createdAt:now-2400000,acceptedAt:now-2100000,readyAt:now-1800000,pickedUpAt:now-1650000,completedAt:now-1600000}
];
let orders=loadOrders();
let activeFilter='all';
let lastNewId=null;
let pickupConfirmationOrderId=null;
function normalizeOrders(list){return list.map(o=>{if(o.status==='completed'){o.status='pickedup';o.pickedUpAt=o.pickedUpAt||o.completedAt||Date.now();}return o;});}
function recoverActiveCustomerOrders(vendorOrders){
 const recovered=[...vendorOrders],knownIds=new Set(recovered.map(order=>String(order.id))),customers=[];
 try{const accounts=JSON.parse(localStorage.getItem('ftnCustomerAccountsV1'));if(Array.isArray(accounts))customers.push(...accounts);}catch{}
 try{const guest=JSON.parse(localStorage.getItem('ftnGuestCustomerV1'));if(guest)customers.push(guest);}catch{}
 customers.forEach(customer=>(customer.orders||[]).forEach(order=>{
  if(knownIds.has(String(order.id))||['completed','cancelled','pickedup'].includes(order.status))return;
  recovered.unshift({
   id:order.id,truckId:order.truckId,truckName:order.truckName,
   customer:order.customerName||customer.preferredName||customer.firstName||'Customer',
   customerMobile:order.customerMobile||customer.mobile||'',customerEmail:order.customerEmail||customer.email||'',
   guestCheckout:Boolean(order.guestCheckout||customer.isGuest),
   items:(order.items||[]).map(item=>({name:item.name,qty:Number(item.qty||item.quantity||1),price:Number(item.price||0),modifiers:item.modifiers||[],instructions:item.instructions||''})),
   subtotal:Number(order.subtotal||0),tax:Number(order.tax||0),total:Number(order.total||0),
   status:order.status==='received'?'new':order.status,time:new Date(order.createdAt||Date.now()).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),
   payment:order.paymentLabel||'Pay at Pickup',paid:true,createdAt:order.createdAt||Date.now()
  });
  knownIds.add(String(order.id));
 }));
 return recovered;
}
function loadOrders(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));const stored=Array.isArray(saved)&&saved.length?saved:seedOrders;return normalizeOrders(recoverActiveCustomerOrders(stored));}catch{return normalizeOrders(recoverActiveCustomerOrders(seedOrders));}}
function saveOrders(){localStorage.setItem(STORAGE_KEY,JSON.stringify(orders));}
function customerStatusForVendorStatus(status){
 if(status==='new')return {status:'received',statusLabel:'Order Received'};
 if(status==='preparing')return {status:'preparing',statusLabel:'Preparing'};
 if(status==='ready')return {status:'ready',statusLabel:'Ready for Pickup'};
 if(status==='pickedup'||status==='completed')return {status:'completed',statusLabel:'Picked Up'};
 if(status==='cancelled')return {status:'cancelled',statusLabel:'Cancelled · Full Refund'};
 return {status,statusLabel:statusLabel(status)};
}
function syncVendorOrderStatusToCustomers(vendorOrder){
 const mapped=customerStatusForVendorStatus(vendorOrder.status),customerStorageKeys=['ftnCustomerAccountsV1','ftnGuestCustomerV1'];
 let changed=false;
 customerStorageKeys.forEach(key=>{
  try{
   const saved=JSON.parse(localStorage.getItem(key));
   const customers=key==='ftnCustomerAccountsV1'?(Array.isArray(saved)?saved:[]):saved?[saved]:[];
   let storageChanged=false;
   customers.forEach(customer=>{
    const customerOrder=(customer.orders||[]).find(order=>String(order.id)===String(vendorOrder.id));
    if(!customerOrder)return;
    Object.assign(customerOrder,mapped,{acceptedAt:vendorOrder.acceptedAt||customerOrder.acceptedAt,readyAt:vendorOrder.readyAt||customerOrder.readyAt,pickedUpAt:vendorOrder.pickedUpAt||customerOrder.pickedUpAt,completedAt:vendorOrder.pickedUpAt||vendorOrder.completedAt||customerOrder.completedAt,lastStatusChangeAt:Date.now()});
    storageChanged=true;
   });
   if(storageChanged){
    localStorage.setItem(key,JSON.stringify(key==='ftnCustomerAccountsV1'?customers:customers[0]));
    changed=true;
   }
  }catch{}
 });
 if(changed&&window.dispatchEvent&&typeof CustomEvent==='function')window.dispatchEvent(new CustomEvent('ftn:customer-orders-updated',{detail:{orderId:vendorOrder.id,status:mapped.status}}));
}
function refreshVendorOrders(){orders=loadOrders();if(!dashboardView.classList.contains('hidden-view'))render();}
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v)}
function itemCount(o){return o.items.reduce((s,i)=>s+Number(i.qty||0),0)}
function safeOrderText(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function itemList(o){return o.items.map(i=>`<li>${i.qty} × ${safeOrderText(i.name)}${i.modifiers?.length?` <small>(${i.modifiers.map(modifier=>safeOrderText(modifier.name)).join(', ')})</small>`:''}${i.instructions?`<br><small><strong>Notes:</strong> ${safeOrderText(i.instructions)}</small>`:''}</li>`).join('')}
function statusLabel(s){return s==='new'?'New Order':s==='preparing'?'Received / Preparing':s==='ready'?'Ready for Pickup':s==='pickedup'?'Picked Up':s==='cancelled'?'Cancelled / Refunded':'Completed'}
function elapsed(from){if(!from)return '00:00';const sec=Math.max(0,Math.floor((Date.now()-from)/1000));const m=Math.floor(sec/60);const s=sec%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function timerMarkup(o){if(o.status==='preparing')return `<div class="timer">⏱ Preparing <span class="live-timer" data-from="${o.acceptedAt||Date.now()}" data-prefix="Preparing">${elapsed(o.acceptedAt)}</span></div>`;if(o.status==='ready')return `<div class="timer">⏱ Waiting <span class="live-timer" data-from="${o.readyAt||Date.now()}" data-prefix="Waiting">${elapsed(o.readyAt)}</span></div>`;if(o.status==='pickedup')return `<div class="timer">✓ Picked up <span class="live-timer" data-from="${o.pickedUpAt||Date.now()}" data-prefix="Picked up">${elapsed(o.pickedUpAt)}</span></div>`;if(o.status==='completed'&&o.completedAt)return `<div class="timer">✓ Completed ${new Date(o.completedAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</div>`;return '';}
function orderActionId(id){return JSON.stringify(String(id)).replace(/&/g,'&amp;').replace(/</g,'\\u003c').replace(/"/g,'&quot;');}
function nextAction(o){const id=orderActionId(o.id);if(o.status==='new')return `<button class="small-button accept" onclick="moveOrder(${id},'preparing')">Accept Order</button>`;if(o.status==='preparing')return `<button class="small-button ready" onclick="moveOrder(${id},'ready')">Ready for Pickup</button>`;if(o.status==='ready')return `<button class="small-button confirm-pickup" onclick="openPickupConfirmation(${id})">Confirm Pickup</button>`;return '';}
function card(o){const flash=o.id===lastNewId?' new-flash':'';const orderHighlight=o.status==='ready'||o.status==='pickedup'?`<div class="order-number-highlight">Order #${o.id}</div>`:'';const code='';const newTag=o.status==='new'?'<span class="new-indicator">NEW</span>':'';return `<article class="order-card status-${o.status}-card${flash}"><div class="order-card-header"><div>${newTag}<h3>Order #${o.id}</h3><div class="order-meta">${o.customer} · ${o.time} · ${itemCount(o)} item${itemCount(o)===1?'':'s'}</div>${orderHighlight}${code}${timerMarkup(o)}</div><div><strong>${money(o.total)}</strong><div><span class="status-badge status-${o.status}">${statusLabel(o.status)}</span></div></div></div><ul class="order-items">${itemList(o)}</ul><div class="order-footer"><span class="order-meta">${o.paid?'Paid':'Unpaid'} · ${o.payment}</span><div class="order-actions"><button class="small-button details" onclick="showDetails(${orderActionId(o.id)})">Order Details</button>${nextAction(o)}</div></div></article>`;}
const lists={new:document.getElementById('newOrders'),preparing:document.getElementById('preparingOrders'),ready:document.getElementById('readyOrders'),pickedup:document.getElementById('pickedUpOrders'),completed:document.getElementById('completedOrders')};
function render(){
 Object.entries(lists).forEach(([s,el])=>{const f=s==='completed'?orders.filter(o=>o.status==='ready'||o.status==='pickedup'):orders.filter(o=>o.status===s);el.innerHTML=f.length?f.map(card).join(''):'<div class="empty-state">No orders in this section.</div>';});
 const counts={new:orders.filter(o=>o.status==='new').length,preparing:orders.filter(o=>o.status==='preparing').length,ready:orders.filter(o=>o.status==='ready').length,pickedup:orders.filter(o=>o.status==='pickedup').length,completed:orders.filter(o=>o.status==='ready'||o.status==='pickedup').length};
 document.getElementById('newOrderCount').textContent=counts.new;document.getElementById('newSummaryCount').textContent=counts.new;document.getElementById('preparingCount').textContent=counts.preparing;document.getElementById('readyCount').textContent=counts.ready;document.getElementById('pickedUpCount').textContent=counts.pickedup;document.getElementById('completedCount').textContent=counts.completed;
 document.getElementById('salesTotal').textContent=money(orders.filter(o=>o.paid).reduce((s,o)=>s+o.total,0));
 document.getElementById('allCount').textContent=orders.length;document.getElementById('tabNewCount').textContent=counts.new;document.getElementById('tabPreparingCount').textContent=counts.preparing;document.getElementById('tabReadyCount').textContent=counts.ready;document.getElementById('tabPickedUpCount').textContent=counts.pickedup;document.getElementById('tabCompletedCount').textContent=counts.completed;
 renderOrdersPage();saveOrders();updateSoundButton();
}
function renderOrdersPage(){const q=(document.getElementById('orderSearch').value||'').trim().toLowerCase();let filtered=activeFilter==='all'?orders:activeFilter==='completed'?orders.filter(o=>o.status==='ready'||o.status==='pickedup'):orders.filter(o=>o.status===activeFilter);if(q)filtered=filtered.filter(o=>String(o.id).includes(q)||o.customer.toLowerCase().includes(q));document.getElementById('allOrdersList').innerHTML=filtered.length?filtered.map(card).join(''):'<div class="empty-state">No matching orders.</div>';}
function updateLiveTimers(){document.querySelectorAll('.live-timer').forEach(el=>{el.textContent=elapsed(Number(el.dataset.from));});}
function notify(text){const t=document.getElementById('toast');t.textContent=text;t.classList.add('show');clearTimeout(window.ftnToast);window.ftnToast=setTimeout(()=>t.classList.remove('show'),2200);}
function tone(type='new'){if(!soundOn)return;try{const C=window.AudioContext||window.webkitAudioContext;const ctx=new C();const osc=ctx.createOscillator();const gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.type='sine';osc.frequency.value=type==='ready'?740:type==='pickup'?880:520;gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.18,ctx.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.35);osc.start();osc.stop(ctx.currentTime+.38);}catch(e){}}
window.moveOrder=(id,status)=>{const o=orders.find(x=>String(x.id)===String(id));if(!o)return;const old=statusLabel(o.status);o.status=status;const stamp=Date.now();if(status==='preparing')o.acceptedAt=stamp;if(status==='ready'){o.readyAt=stamp;tone('ready');}if(status==='pickedup'){o.pickedUpAt=stamp;tone('pickup');}if(status==='completed')o.completedAt=stamp;syncVendorOrderStatusToCustomers(o);lastNewId=null;render();closeModal();notify(`Order #${id}: ${old} → ${statusLabel(status)}`);};
window.openPickupConfirmation=id=>{const o=orders.find(x=>String(x.id)===String(id));if(!o)return;pickupConfirmationOrderId=id;const modal=document.getElementById('pickupModal');const pickupCode=String(o.id).replace(/\D/g,'');modal.dataset.orderId=String(o.id);modal.dataset.expectedOrderNumber=pickupCode;document.getElementById('pickupOrderNumber').textContent=`Order #${o.id}`;document.getElementById('pickupCustomer').textContent=o.customer;document.getElementById('orderNumber').value='';document.getElementById('pickupError').textContent='';document.getElementById('pickupDemoCode').textContent=pickupCode;modal.classList.remove('hidden');setTimeout(()=>document.getElementById('orderNumber').focus(),50);};
function closePickupModal(){document.getElementById('pickupModal').classList.add('hidden');pickupConfirmationOrderId=null;}
document.getElementById('confirmPickupButton').addEventListener('click',()=>{const modal=document.getElementById('pickupModal');const orderId=modal.dataset.orderId;const o=orders.find(x=>String(x.id)===String(orderId));if(!o){document.getElementById('pickupError').textContent='This order could not be found. Close the window and try again.';return;}const entered=document.getElementById('orderNumber').value.replace(/\D/g,'');const expected=String(o.id).replace(/\D/g,'');if(!entered){document.getElementById('pickupError').textContent='Enter the order number.';return;}if(entered!==expected){document.getElementById('pickupError').textContent=`Order number does not match Order #${o.id}.`;return;}document.getElementById('pickupError').textContent='✓ Order number verified.';document.getElementById('pickupError').classList.add('success-message');setTimeout(()=>{document.getElementById('pickupError').classList.remove('success-message');closePickupModal();moveOrder(o.id,'pickedup');},500);});
document.getElementById('useDemoCodeButton').addEventListener('click',()=>{const modal=document.getElementById('pickupModal');document.getElementById('orderNumber').value=modal.dataset.expectedOrderNumber||'';document.getElementById('pickupError').textContent='';document.getElementById('orderNumber').focus();});
document.getElementById('orderNumber').addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,12);document.getElementById('pickupError').textContent='';});
document.getElementById('cancelPickupButton').addEventListener('click',closePickupModal);document.getElementById('pickupModal').addEventListener('click',e=>{if(e.target.id==='pickupModal')closePickupModal();});
document.getElementById('orderNumber').addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('confirmPickupButton').click();});
window.showDetails=id=>{const o=orders.find(x=>String(x.id)===String(id));if(!o)return;document.getElementById('modalContent').innerHTML=`<p class="eyebrow">Order Details</p><h2>Order #${o.id}</h2>${o.status==='ready'||o.status==='pickedup'?`<div class="order-number-highlight">Order #${o.id}</div>`:''}<div class="detail-line"><span>Customer</span><strong>${o.customer}</strong></div><div class="detail-line"><span>Time Ordered</span><strong>${o.time}</strong></div><div class="detail-line"><span>Status</span><strong>${statusLabel(o.status)}</strong></div><div class="detail-line"><span>Payment</span><strong>${o.paid?'Paid':'Unpaid'} · ${o.payment}</strong></div>${timerMarkup(o)}<h3>Items</h3><ul>${itemList(o)}</ul><div class="detail-line"><span>Subtotal</span><strong>${money(o.subtotal)}</strong></div><div class="detail-line"><span>Tax</span><strong>${money(o.tax)}</strong></div><div class="detail-line"><span>Total</span><strong>${money(o.total)}</strong></div><div class="modal-status-actions">${nextAction(o)}</div>`;document.getElementById('orderModal').classList.remove('hidden');};
function closeModal(){document.getElementById('orderModal').classList.add('hidden');}
document.getElementById('closeModal').addEventListener('click',closeModal);document.getElementById('orderModal').addEventListener('click',e=>{if(e.target.id==='orderModal')closeModal();});

document.querySelectorAll('.nav-link[data-page]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-link').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.app-page').forEach(p=>p.classList.add('hidden-view'));document.getElementById(`${btn.dataset.page}Page`).classList.remove('hidden-view');if(btn.dataset.page==='orders')refreshVendorOrders();if(btn.dataset.page==='menu'&&typeof renderMenu==='function')renderMenu();const map={dashboard:['Vendor Dashboard','Capital City Eats'],orders:['Order Management','Orders'],menu:['Menu Management','Menu'],reports:['Sales & Performance','Reports'],settings:['Vendor Profile','Settings']};document.getElementById('pageEyebrow').textContent=map[btn.dataset.page][0];document.getElementById('pageTitle').textContent=map[btn.dataset.page][1];}));
document.querySelectorAll('.filter-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;renderOrdersPage();}));
document.getElementById('orderSearch').addEventListener('input',renderOrdersPage);
document.getElementById('simulateOrderButton').addEventListener('click',()=>{const names=['Jordan','Taylor','Chris','Alicia','Robert','Nina'];const choices=[[{name:'Smash Burger',qty:2,price:11.50},{name:'Seasoned Fries',qty:1,price:4.50}],[{name:'Chicken Tacos',qty:3,price:5.25},{name:'Lemonade',qty:2,price:4.00}],[{name:'BBQ Bowl',qty:1,price:16.00},{name:'Mac & Cheese',qty:1,price:5.50}]];const items=choices[Math.floor(Math.random()*choices.length)];const subtotal=items.reduce((s,i)=>s+i.qty*i.price,0);const tax=Number((subtotal*.06).toFixed(2));const id=Math.max(...orders.map(o=>o.id))+1;const createdAt=Date.now();orders.unshift({id,customer:names[Math.floor(Math.random()*names.length)],items,subtotal,tax,total:Number((subtotal+tax).toFixed(2)),status:'new',time:new Date(createdAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),payment:'Credit Card',paid:true,createdAt});lastNewId=id;render();tone('new');notify(`New order #${id} received`);setTimeout(()=>{lastNewId=null;document.querySelectorAll('.new-flash').forEach(el=>el.classList.remove('new-flash'));},3800);});
function updateSoundButton(){const b=document.getElementById('soundToggleButton');if(b)b.textContent=soundOn?'🔔 Sound On':'🔕 Sound Off';}
document.getElementById('soundToggleButton').addEventListener('click',()=>{soundOn=!soundOn;localStorage.setItem(SOUND_KEY,soundOn?'on':'off');updateSoundButton();if(soundOn)tone('new');notify(soundOn?'Order sounds enabled':'Order sounds muted');});
document.getElementById('onlineToggle').addEventListener('change',e=>{const on=e.target.checked;document.getElementById('statusText').textContent=on?'Online':'Offline';document.getElementById('statusDot').className=`status-dot ${on?'online':'offline'}`;notify(on?'Truck is online':'Truck is offline');});
document.getElementById('logoutButton').addEventListener('click',showLogin);
if(window.addEventListener){
 window.addEventListener('ftn:vendor-orders-updated',refreshVendorOrders);
 window.addEventListener('storage',event=>{if(event.key===STORAGE_KEY)refreshVendorOrders();});
}
setInterval(()=>{if(!dashboardView.classList.contains('hidden-view')){updateLiveTimers();}},1000);
if(localStorage.getItem('ftnVendorLoggedIn')==='true')showDashboard();else updateSoundButton();


// Phase 3 Menu Management
const MENU_STORAGE_KEY='ftnVendorMenuV0400';
const CATEGORY_STORAGE_KEY='ftnVendorCategoriesV0400';
const defaultCategories=['Featured','Burgers','Entrées','Tacos','Sides','Drinks'];
const defaultMenuItems=[
{id:1,name:'Classic Cheeseburger',category:'Burgers',price:11.50,description:'Seasoned beef patty, American cheese, lettuce, tomato, pickles, and house sauce.',available:true,featured:true,image:'',order:1},
{id:2,name:'Loaded Nachos',category:'Entrées',price:12.00,description:'Crispy tortilla chips with cheese, seasoned meat, pico de gallo, and crema.',available:true,featured:false,image:'',order:2},
{id:3,name:'Chicken Tacos',category:'Tacos',price:5.25,description:'Grilled chicken, cabbage slaw, pico de gallo, and lime crema.',available:true,featured:true,image:'',order:3},
{id:4,name:'Seasoned Fries',category:'Sides',price:4.50,description:'Crispy fries tossed in the truck’s signature seasoning.',available:true,featured:false,image:'',order:4},
{id:5,name:'Sweet Potato Fries',category:'Sides',price:5.50,description:'Crispy sweet potato fries with dipping sauce.',available:false,featured:false,image:'',order:5},
{id:6,name:'Fresh Lemonade',category:'Drinks',price:4.00,description:'Fresh-squeezed lemonade served cold.',available:true,featured:false,image:'',order:6}
];
let categories=loadCategories();
let menuItems=loadMenuItems();
let pendingMenuImage='';
function loadCategories(){try{const x=JSON.parse(localStorage.getItem(CATEGORY_STORAGE_KEY));return Array.isArray(x)&&x.length?x:defaultCategories.slice();}catch{return defaultCategories.slice();}}
function loadMenuItems(){try{const x=JSON.parse(localStorage.getItem(MENU_STORAGE_KEY));return Array.isArray(x)&&x.length?x.map((i,n)=>({...i,featured:Boolean(i.featured),order:Number(i.order)||n+1})):defaultMenuItems.map(i=>({...i}));}catch{return defaultMenuItems.map(i=>({...i}));}}
function saveMenuData(){localStorage.setItem(MENU_STORAGE_KEY,JSON.stringify(menuItems));localStorage.setItem(CATEGORY_STORAGE_KEY,JSON.stringify(categories));}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function categoryIcon(c){c=c.toLowerCase();return c.includes('drink')?'🥤':c.includes('taco')?'🌮':c.includes('side')?'🍟':c.includes('dessert')?'🍰':c.includes('chicken')?'🍗':'🍔';}
function menuCard(item){return `<article class="menu-item-card ${item.available?'':'sold-out'}" draggable="true" data-item-id="${item.id}"><div class="drag-handle" title="Drag to reorder">☰</div><div class="menu-item-image">${item.image?`<img src="${item.image}" alt="${escapeHtml(item.name)}" />`:`<span class="menu-item-placeholder">${categoryIcon(item.category)}</span>`}${item.featured?'<span class="featured-chip">★ Featured</span>':''}<span class="availability-chip ${item.available?'':'soldout'}">${item.available?'Available':'Sold Out'}</span></div><div class="menu-item-body"><div class="menu-item-title-row"><h3>${escapeHtml(item.name)}</h3><span class="menu-price">${money(Number(item.price))}</span></div><span class="menu-category">${escapeHtml(item.category)}</span><p class="menu-description">${escapeHtml(item.description||'No description added.')}</p><div class="menu-item-actions"><button class="small-button details" type="button" onclick="editMenuItem(${item.id})">Edit</button><button class="small-button danger-button" type="button" onclick="deleteMenuItem(${item.id})">Delete</button><button class="small-button menu-toggle-button ${item.available?'':'soldout'}" type="button" onclick="toggleMenuAvailability(${item.id})">${item.available?'Mark Sold Out':'Make Available'}</button></div></div></article>`;}
function renderMenu(){const grid=document.getElementById('menuItemsGrid');if(!grid)return;const q=(document.getElementById('menuSearch')?.value||'').trim().toLowerCase();const category=document.getElementById('menuCategoryFilter')?.value||'all';const availability=document.getElementById('menuAvailabilityFilter')?.value||'all';const sorted=[...menuItems].sort((a,b)=>(categories.indexOf(a.category)-categories.indexOf(b.category))||(a.order-b.order));const filtered=sorted.filter(item=>(!q||item.name.toLowerCase().includes(q)||(item.description||'').toLowerCase().includes(q)||item.category.toLowerCase().includes(q))&&(category==='all'||item.category===category)&&(availability==='all'||(availability==='available'?item.available:!item.available)));grid.innerHTML=filtered.length?filtered.map(menuCard).join(''):'<div class="menu-empty"><strong>No menu items found.</strong><br />Add an item or change your filters.</div>';document.getElementById('menuTotalCount').textContent=menuItems.length;document.getElementById('menuAvailableCount').textContent=menuItems.filter(i=>i.available).length;document.getElementById('menuSoldOutCount').textContent=menuItems.filter(i=>!i.available).length;document.getElementById('menuCategoryCount').textContent=categories.length;const select=document.getElementById('menuCategoryFilter');const current=select.value;select.innerHTML='<option value="all">All Categories</option>'+categories.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join('');if(current==='all'||categories.includes(current))select.value=current;wireItemDragDrop();saveMenuData();}
function populateCategorySelect(selected=''){const s=document.getElementById('menuItemCategory');s.innerHTML=categories.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join('');s.value=categories.includes(selected)?selected:(categories[0]||'');}
function openMenuItemModal(item=null){pendingMenuImage=item?.image||'';document.getElementById('menuItemModalTitle').textContent=item?'Edit Menu Item':'Add Menu Item';document.getElementById('menuItemId').value=item?.id||'';document.getElementById('menuItemName').value=item?.name||'';populateCategorySelect(item?.category||'');document.getElementById('menuItemPrice').value=item?.price??'';document.getElementById('menuItemDescription').value=item?.description||'';document.getElementById('menuItemAvailable').checked=item?Boolean(item.available):true;document.getElementById('menuItemFeatured').checked=item?Boolean(item.featured):false;document.getElementById('menuItemImage').value='';document.getElementById('menuFormError').textContent='';document.getElementById('menuItemModal').classList.remove('hidden');setTimeout(()=>document.getElementById('menuItemName').focus(),50);}
function closeMenuItemModal(){document.getElementById('menuItemModal').classList.add('hidden');pendingMenuImage='';}
window.editMenuItem=id=>{const item=menuItems.find(i=>i.id===id);if(item)openMenuItemModal(item);};
window.toggleMenuAvailability=id=>{const item=menuItems.find(i=>i.id===id);if(!item)return;item.available=!item.available;renderMenu();notify(`${item.name} is now ${item.available?'available':'sold out'}`);};
window.deleteMenuItem=id=>{const item=menuItems.find(i=>i.id===id);if(!item)return;if(!window.confirm(`Delete ${item.name} from the menu?`))return;menuItems=menuItems.filter(i=>i.id!==id);renderMenu();notify(`${item.name} deleted`);};
function wireItemDragDrop(){let dragged=null;document.querySelectorAll('.menu-item-card[draggable="true"]').forEach(card=>{card.addEventListener('dragstart',()=>{dragged=Number(card.dataset.itemId);card.classList.add('dragging')});card.addEventListener('dragend',()=>card.classList.remove('dragging'));card.addEventListener('dragover',e=>e.preventDefault());card.addEventListener('drop',e=>{e.preventDefault();const target=Number(card.dataset.itemId);if(!dragged||dragged===target)return;const a=menuItems.findIndex(i=>i.id===dragged),b=menuItems.findIndex(i=>i.id===target);const [m]=menuItems.splice(a,1);menuItems.splice(b,0,m);menuItems.forEach((i,n)=>i.order=n+1);renderMenu();notify('Menu order updated');});});}
function renderCategories(){const list=document.getElementById('categoryList');list.innerHTML=categories.map((c,i)=>`<div class="category-row" draggable="true" data-category="${escapeHtml(c)}"><span class="category-drag">☰</span><input class="category-name-input" value="${escapeHtml(c)}" aria-label="Category name" /><span class="category-item-count">${menuItems.filter(x=>x.category===c).length} items</span><button class="small-button details save-category" data-old="${escapeHtml(c)}">Save</button><button class="small-button danger-button delete-category" data-name="${escapeHtml(c)}">Delete</button></div>`).join('');wireCategoryEvents();}
function wireCategoryEvents(){document.querySelectorAll('.save-category').forEach(b=>b.onclick=()=>{const row=b.closest('.category-row'),old=b.dataset.old,newName=row.querySelector('input').value.trim();if(!newName||categories.includes(newName)&&newName!==old){document.getElementById('categoryFormError').textContent='Enter a unique category name.';return;}categories[categories.indexOf(old)]=newName;menuItems.forEach(i=>{if(i.category===old)i.category=newName});document.getElementById('categoryFormError').textContent='';renderCategories();renderMenu();notify('Category updated');});document.querySelectorAll('.delete-category').forEach(b=>b.onclick=()=>{const name=b.dataset.name,count=menuItems.filter(i=>i.category===name).length;if(count){document.getElementById('categoryFormError').textContent=`Move or delete the ${count} item(s) in ${name} before deleting it.`;return;}if(categories.length===1){document.getElementById('categoryFormError').textContent='At least one category is required.';return;}categories=categories.filter(c=>c!==name);renderCategories();renderMenu();notify('Category deleted');});let dragged='';document.querySelectorAll('.category-row').forEach(row=>{row.addEventListener('dragstart',()=>{dragged=row.dataset.category;row.classList.add('dragging')});row.addEventListener('dragend',()=>row.classList.remove('dragging'));row.addEventListener('dragover',e=>e.preventDefault());row.addEventListener('drop',e=>{e.preventDefault();const target=row.dataset.category;if(!dragged||dragged===target)return;const a=categories.indexOf(dragged),b=categories.indexOf(target);categories.splice(b,0,categories.splice(a,1)[0]);renderCategories();renderMenu();notify('Category order updated');});});}
function renderCustomerPreview(){const content=document.getElementById('customerPreviewContent');let html='';const featured=menuItems.filter(i=>i.featured).sort((a,b)=>a.order-b.order);const section=(title,items)=>items.length?`<section class="customer-category"><h3>${escapeHtml(title)}</h3><div class="customer-menu-grid">${items.map(customerCard).join('')}</div></section>`:'';html+=section('★ Featured Favorites',featured);categories.filter(c=>c!=='Featured').forEach(c=>{html+=section(c,menuItems.filter(i=>i.category===c).sort((a,b)=>a.order-b.order));});content.innerHTML=html||'<p class="menu-empty">No menu items yet.</p>';}
function customerCard(item){return `<article class="customer-menu-card ${item.available?'':'sold-out'}"><div class="customer-menu-image">${item.image?`<img src="${item.image}" alt="${escapeHtml(item.name)}">`:`<span>${categoryIcon(item.category)}</span>`}${item.available?'':'<div class="sold-out-overlay">SOLD OUT</div>'}</div><div class="customer-menu-body"><h4>${escapeHtml(item.name)}</h4><p>${escapeHtml(item.description||'')}</p><div class="customer-menu-footer"><strong>${money(Number(item.price))}</strong><button class="primary-button" ${item.available?'':'disabled'}>${item.available?'Add to Order':'Unavailable'}</button></div></div></article>`;}

document.getElementById('addMenuItemButton').addEventListener('click',()=>openMenuItemModal());
document.getElementById('closeMenuItemModal').addEventListener('click',closeMenuItemModal);document.getElementById('cancelMenuItemButton').addEventListener('click',closeMenuItemModal);document.getElementById('menuItemModal').addEventListener('click',e=>{if(e.target.id==='menuItemModal')closeMenuItemModal();});
document.getElementById('menuItemImage').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){document.getElementById('menuFormError').textContent='Please select an image file.';return;}if(file.size>2*1024*1024){document.getElementById('menuFormError').textContent='Use an image smaller than 2 MB.';e.target.value='';return;}const reader=new FileReader();reader.onload=()=>{pendingMenuImage=String(reader.result||'');document.getElementById('menuFormError').textContent='';};reader.readAsDataURL(file);});
document.getElementById('menuItemForm').addEventListener('submit',e=>{e.preventDefault();const id=Number(document.getElementById('menuItemId').value||0),name=document.getElementById('menuItemName').value.trim(),category=document.getElementById('menuItemCategory').value,price=Number(document.getElementById('menuItemPrice').value),description=document.getElementById('menuItemDescription').value.trim(),available=document.getElementById('menuItemAvailable').checked,featured=document.getElementById('menuItemFeatured').checked,error=document.getElementById('menuFormError');if(!name||!category||!Number.isFinite(price)||price<0){error.textContent='Enter an item name, category, and valid price.';return;}if(id){const item=menuItems.find(i=>i.id===id);if(item)Object.assign(item,{name,category,price,description,available,featured,image:pendingMenuImage});notify(`${name} updated`);}else{const nextId=menuItems.length?Math.max(...menuItems.map(i=>Number(i.id)||0))+1:1;menuItems.push({id:nextId,name,category,price,description,available,featured,image:pendingMenuImage,order:menuItems.length+1});notify(`${name} added`);}closeMenuItemModal();renderMenu();});
['menuSearch','menuCategoryFilter','menuAvailabilityFilter'].forEach(id=>document.getElementById(id).addEventListener(id==='menuSearch'?'input':'change',renderMenu));
document.getElementById('manageCategoriesButton').onclick=()=>{document.getElementById('categoryFormError').textContent='';renderCategories();document.getElementById('categoryModal').classList.remove('hidden');};
document.getElementById('closeCategoryModal').onclick=()=>document.getElementById('categoryModal').classList.add('hidden');document.getElementById('categoryModal').addEventListener('click',e=>{if(e.target.id==='categoryModal')e.currentTarget.classList.add('hidden')});
document.getElementById('categoryForm').addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('newCategoryName'),name=input.value.trim();if(!name||categories.includes(name)){document.getElementById('categoryFormError').textContent='Enter a unique category name.';return;}categories.push(name);input.value='';document.getElementById('categoryFormError').textContent='';renderCategories();renderMenu();notify('Category added');});
document.getElementById('previewCustomerMenuButton').onclick=()=>{renderCustomerPreview();document.getElementById('customerPreviewModal').classList.remove('hidden')};document.getElementById('closeCustomerPreviewModal').onclick=()=>document.getElementById('customerPreviewModal').classList.add('hidden');document.getElementById('customerPreviewModal').addEventListener('click',e=>{if(e.target.id==='customerPreviewModal')e.currentTarget.classList.add('hidden')});
renderMenu();
